<?php
defined('BASEPATH') OR exit('No direct script access allowed');
/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
/*$config[ 'base_url' ]	=	((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ?  "https" : "http");
$config[ 'base_url' ] 	.=  "://".$_SERVER['HTTP_HOST'];
$config[ 'base_url' ]	.=  str_replace(basename($_SERVER['SCRIPT_NAME']),"",$_SERVER['SCRIPT_NAME']);*/
//$config['base_url'] = 'http://'.$_SERVER['SERVER_NAME'].'/taportal/';
$config[ 'base_url' ]	=  'https://iibf.esdsconnect.com/';
// $config[ 'base_url' ] = 'https://115.124.108.36/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';
/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';
/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';
/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';
/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';
/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;
/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';
/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;
/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-=,';
/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';
/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;
/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
//$config['log_path'] = '';
$config['log_path'] = APPPATH.'../error_logs/';
/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';
/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;
/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';
/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';
/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';
/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;
/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
$config['encryption_key'] = '';
/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
//file base sesion
$config['encryption_key'] = 'somekey';
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = BASEPATH . 'cache/sessions/';
$config['sess_match_ip'] = FALSE; 
$config['sess_time_to_update'] = 3600;
$config['sess_regenerate_destroy'] = false;
//DB base session
/*$config['sess_driver'] = 'database';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
//$config['sess_save_path'] = NULL;
$config['sess_save_path'] = 'ci_sessions';
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;*/
/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= TRUE;
$config['cookie_httponly'] 	= TRUE;
/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| This is particularly useful for portability between UNIX-based OSes,
| (usually \n) and Windows (\r\n).
|
*/
$config['standardize_newlines'] = FALSE;
/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;
/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
/*$config['csrf_protection'] = FALSE;
if (isset($_SERVER["REQUEST_URI"])) {
    if(stripos($_SERVER["REQUEST_URI"],'admin/login') !== FALSE ) {
        $config['csrf_protection'] = TRUE;
    }
} */
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();
/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = TRUE;
/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';
/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;
/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';
// Member registration fee
$config['member_reg_fee'] = 1725;
//$config['member_reg_fee'] = 1;
//$config['member_reg_fee'] = 1;
// Duplicate ID card fee
$config['dup_id_card_fee'] = 115;
//$config['dup_id_card_fee'] = 1;
//Amp amount self spensor
$config['amp_fullpay_amount'] = 112750;
$config['amp_first_installment'] = 78250;
$config['amp_second_installment'] = 17250;
$config['amp_third_installment'] = 17250;
/*//SBI ePay configuration
// UAT env params
//$config['sbi_m_key'] = "fBc5628ybRQf88f/aqDUOQ==";
$config['sbi_m_key'] = "fIE7EwnuIt/DjAdz1yyfoA==";
//$config['sbi_merchIdVal'] = "1000003";
$config['sbi_merchIdVal'] = "1000205";
$config['sbi_AggregatorId'] = "SBIEPAY";
$config['sbi_pg_form_url'] = "https://test.sbiepay.com/secure/AggregatorHostedListener";
$config['sb_test_mode'] = TRUE; //keep false on production, true for test
$config['sbi_query_form_url'] = "https://test.sbiepay.com/secure/AggMerchantStatusQueryAction";
$config['sbi_refund_form_url'] = "https://test.sbiepay.com/secure/AggregatorRefundRequest";
$config['sbi_cancel_form_url'] = "";
$config['sbi_status_query_api'] = "https://test.sbiepay.com/payagg/orderStatusQuery/getOrderStatusQuery";
$config['sbi_refund_canc_api'] = "https://test.sbiepay.com/payagg/orderRefundCancellation/bookRefundCancellation";*/
/* 09-07-2020 > Mail > Domain change
$config['sbi_m_key'] = "QanfIfEDIAIzfxUoFm4X7g==";
$config['sbi_merchIdVal'] = "1000169";
$config['sbi_AggregatorId'] = "SBIEPAY";
$config['sbi_pg_form_url'] = "https://www.sbiepay.com/secure/AggregatorHostedListener";
$config['sb_test_mode'] = FALSE; //keep false on production, true for test
$config['wallet_test_mode'] = FALSE; //keep false on production, true for test
$config['sbi_query_form_url'] = "https://www.sbiepay.com/secure/AggMerchantStatusQueryAction";
$config['sbi_refund_form_url'] = "https://www.sbiepay.com/secure/AggregatorRefundRequest";
$config['sbi_cancel_form_url'] = "";
$config['sbi_status_query_api'] = "https://www.sbiepay.com/payagg/orderStatusQuery/getOrderStatusQuery";
$config['sbi_refund_canc_api'] = "";
*/

//key value removed on 4th july 2022 to disable sbi gateway riginal value is QanfIfEDIAIzfxUoFm4X7g==
$config['sbi_m_key'] = "QanfIfEDIAIzfxUoFm4X7g==";
$config['sbi_merchIdVal'] = "1000169";
$config['sbi_AggregatorId'] = "SBIEPAY";

/* $config['sbi_m_key'] = "----";
$config['sbi_merchIdVal'] = "----";
$config['sbi_AggregatorId'] = "----"; */


$config['sbi_pg_form_url'] = "https://www.sbiepay.sbi/secure/AggregatorHostedListener";
$config['sb_test_mode'] = FALSE; //keep false on production, true for test
$config['wallet_test_mode'] = FALSE; //keep false on production, true for test
$config['sbi_query_form_url'] = "https://www.sbiepay.sbi/secure/AggMerchantStatusQueryAction";
$config['sbi_refund_form_url'] = "https://www.sbiepay.sbi/secure/AggregatorRefundRequest";
$config['sbi_cancel_form_url'] = "";
$config['sbi_status_query_api'] = "https://www.sbiepay.sbi/payagg/orderStatusQuery/getOrderStatusQuery";
$config['sbi_refund_canc_api'] = "";
////csc wallet configuration
$config['csc_product_id'] = "6991026292";
//BillDesk configuration
// UAT env params
$config['bd_MerchantID'] = "IIBF";
$config['bd_SecurityID'] = "iibf";
$config['bd_ChecksumKey'] = "sRKUUgdDrMGL";
$config['bd_pg_form_url'] = "https://pgi.billdesk.com/pgidsk/PGIMerchantPayment";
$config['bd_test_mode'] = TRUE; //keep false on production, true for test
//$config['bd_query_form_url'] = "https://test.sbiepay.com/secure/AggMerchantStatusQueryAction";
//$config['bd_refund_form_url'] = "https://test.sbiepay.com/secure/AggregatorRefundRequest";


//START : LATEST BILLDESK KEYS ADDED BY SAGAR & VISHAL ON 09-06-2022
$config['BD_KEY'] = "dJv9FHSYShS4U95pV9zpkREG4HIyYGjH";
$config['BD_MERCID'] = "INDINSBAF";
$config['BD_CURRENCY'] = "356";
$config['BD_GSTIN'] = "12344567";
$config['BD_ALG'] = "HS256";
$config['BD_CLIENTID'] = "indinsbaf";
$config['BD_BILLDESK_URL'] = "https://api.billdesk.com/payments/ve1_2/orders/create"; //Create Order
$config['BD_SERVICE_URL'] = "https://api.billdesk.com/payments/ve1_2/transactions/get"; //Retrieve Transaction
$config['BD_REFUND_URL'] = "https://api.billdesk.com/payments/ve1_2/refunds/create"; //Create Refund
$config['BD_REFUND_STATUS_URL'] = "https://api.billdesk.com/payments/ve1_2/refunds/get"; //Retrieve Refund
//END : LATEST BILLDESK KEYS ADDED BY SAGAR & VISHAL ON 09-06-2022



//password key (Sensitive keys : Do not change it [[Important]])
$config['pass_key'] = 'jIDSLo4xG6xsedD';  // for member and non member
$config['admin_pass_key'] = 'DaeJVjhsdHAG7vj';  // for master admin module
$config['dra_pass_key'] = 'Oiuies5KshAHs2';  // for DRA institute login
$config['dra_admin_pass_key'] = 'Pojsdf6bjLnfwyi';  // for DRA admin login
$config['exam_apply_gateway'] = 'sbi';  // Get Exam apply gate-way during exam apply
$config['wallet_exam_apply_fee'] = '1';
//$config['exam_apply_fee'] = '1';  // Get Exam apply gate-way during exam apply
//$config['DISA_apply_fee'] = '575';  // Get DISA Exam apply gate-way during exam apply
$config['DISA_apply_fee'] = '500';  // Get DISA Exam apply gate-way during exam apply
$config['DISA_sgst_rate'] = '9';
$config['DISA_sgst_amt'] = '45';
$config['DISA_cgst_rate'] = '9';
$config['DISA_cgst_amt'] = '45';
$config['DISA_cs_total'] = '590';
$config['Cisi_apply_fee'] = '1000';  // Get CISI Exam apply gate-way during exam apply
$config['Cisi_sgst_rate'] = '9';
$config['Cisi_sgst_amt'] = '90';
$config['Cisi_cgst_rate'] = '9';
$config['Cisi_cgst_amt'] = '90';
$config['Cisi_cs_total'] = '1180';
// apply for  Duplicate I-card intra
$config['Dup_Id_apply_fee'] = '100';  
$config['Dup_Id_sgst_rate'] = '9';
$config['Dup_Id_sgst_amt'] = '9';
$config['Dup_Id_cgst_rate'] = '9';
$config['Dup_Id_cgst_amt'] = '9';
$config['Dup_Id_cs_total'] = '118';
// apply for  Duplicate I-card inter
$config['Dup_Id_igst_amt'] = '18';
$config['Dup_Id_igst_rate'] = '18';
$config['Dup_Id_igst_tot'] = '118';
$config['elective_exam_code'] = array("62","63","64","65","66","67","68","69","70","71","72");
$config['kyc_start_date'] = '2017-06-01';
//member registration (member type = O) set GST rate
$config['cgst_rate'] = '9';
$config['sgst_rate'] = '9';
$config['igst_rate'] = '18';
$config['fee_amt'] = '1500';
//$config['fee_amt'] = '1';
$config['sgst_amt'] = '135';
$config['cgst_amt'] = '135';
$config['igst_amt'] = '270';
$config['cs_total'] = '1770';
//$config['cs_total'] = '2';
$config['igst_total'] = '1770';
//$config['igst_total'] = '3';
$config['DISA_service_code'] = '999294';
$config['Cisi_service_code'] = '999294';
$config['exam_service_code'] = '999294';
$config['reg_service_code'] = '999599';
$config['Dup_Id_service_code'] = '999799';     // service code for duplicated idcard 
$config['Dup_cert_service_code'] = '999799';     // service code for duplicated certificate 
//$yearnow= date("y");
//$yearnext=date("y")+1;
$yearnow= '22';
$yearnext='23';
//for CPD
$config['cpd_service_code'] = '999799'; 
$config['CPD_invoice_no_prefix'] = 'ACPD/'.$yearnow.'-'.$yearnext.'/';
$config['CPD_invoice_no_prefix_jammu'] = 'ACPDJK/'.$yearnow.''.$yearnext.'/';
$config['CPD_apply_fee'] = '1000';  
$config['CPD_sgst_rate'] = '9';
$config['CPD_sgst_amt'] = '90';
$config['CPD_cgst_rate'] = '9';
$config['CPD_cgst_amt'] = '90';
$config['CPD_cs_total'] = '1180';
$config['CPD_igst_amt'] = '180';
$config['CPD_igst_rate'] = '18';
$config['CPD_igst_tot'] = '1180';
//$config['exam_invoice_no_prefix'] = 'EXM/'.$yearnow.'-'.$yearnext.'/';
//$config['mem_invoice_no_prefix'] = 'MEM/'.$yearnow.'-'.$yearnext.'/';
//for jammu region
//$config['exam_invoice_no_prefix_jammu'] = 'EXM/'.$yearnow.'-'.$yearnext.'/J&K/';
//$config['mem_invoice_no_prefix_jammu'] = 'MEM/'.$yearnow.'-'.$yearnext.'/J&K/';
//Member Exam
$config['exam_invoice_no_prefix'] = 'EX/'.$yearnow.'-'.$yearnext.'/';
$config['exam_invoice_no_prefix_jammu'] = 'EX/JK/'.$yearnow.$yearnext.'/'; 
//For ELearning
$config['El_exam_invoice_no_prefix'] = 'SPL/'.$yearnow.'-'.$yearnext.'/';
//Member Registration
$config['mem_invoice_no_prefix'] = 'M/'.$yearnow.'-'.$yearnext.'/';
$config['mem_invoice_no_prefix_jammu'] = 'M/JK/'.$yearnow.$yearnext.'/';
//DRA Exam 
$config['draexam_invoice_no_prefix'] = 'EDN/'.$yearnow.'-'.$yearnext.'/';
//garp-exam
$config['garp_invoice_no_prefix'] = 'GRP/'.$yearnow.'-'.$yearnext.'/';
//Disa  invoice prefix format
//$config['DISA_invoice_no_prefix'] = 'EXM/DUP-CERT/'.$yearnow.'-'.$yearnext.'/';
$config['DISA_invoice_no_prefix'] = 'EDI/'.$yearnow.'-'.$yearnext.'/';
$config['Cisi_invoice_no_prefix'] = 'CIS/'.$yearnow.'-'.$yearnext.'/'; 
//prefix for duplicate id card 
//$config['Dup_Id_invoice_no_prefix'] = 'MEM/DUPICARD/'.$yearnow.'-'.$yearnext.'/';
//$config['Dup_Id_invoice_no_prefix_jammu'] = 'MEM/DUPICARD/'.$yearnow.'-'.$yearnext.'/J&K/';
$config['Dup_Id_invoice_no_prefix'] = 'MDIC/'.$yearnow.'-'.$yearnext.'/';
$config['Dup_Id_invoice_no_prefix_jammu'] = 'MDICJK/'.$yearnow.$yearnext.'/';
// Duplicate Certificate
$config['Dup_cert_apply_fee'] = '200';  // apply for  Duplicate I-cert intra
$config['Dup_cert_sgst_rate'] = '9';
$config['Dup_cert_sgst_amt'] = '18';
$config['Dup_cert_cgst_rate'] = '9';
$config['Dup_cert_cgst_amt'] = '18';
$config['Dup_cert_cs_total'] = '236';
// apply for  Duplicate I-cert inter
$config['Dup_cert_igst_amt'] = '36';
$config['Dup_cert_igst_rate'] = '18';
$config['Dup_cert_igst_tot'] = '236';
// GARP Set GST rate
$config['garp_cgst_rate'] = '9';
$config['garp_sgst_rate'] = '9';
$config['garp_igst_rate'] = '18';
//for duplicate certificate
//$config['Dup_cert_invoice_no_prefix'] = 'EXM/DUP-CERT/'.$yearnow.'-'.$yearnext.'/';//prefix for duplicate id card 
//$config['Dup_cert_invoice_no_prefix_jammu'] = 'EXM/DUP-CERT/'.$yearnow.'-'.$yearnext.'/J&K/';
$config['Dup_cert_invoice_no_prefix'] = 'EDC/'.$yearnow.'-'.$yearnext.'/';//prefix for duplicate id card 
$config['Dup_cert_invoice_no_prefix_jammu'] = 'EDCJK/'.$yearnow.''.$yearnext.'/';
#-------------Fin Quest------------#
//$fromyear= date("y");
//$toyear=date("y")+1;
$fromyear= '22';
$toyear='23';
//intra 
$config['FinQuest_apply_fee'] = '500';  
$config['FinQuest_sgst_rate'] = '9';
$config['FinQuest_sgst_amt'] = '45';
$config['FinQuest_cgst_rate'] = '9';
$config['FinQuest_cgst_amt'] = '45';
$config['FinQuest_cs_total'] = '590';
//inter
$config['FinQuest_igst_amt'] = '90';
$config['FinQuest_igst_rate'] = '18';
$config['FinQuest_igst_tot'] = '590';
//validation period for finquest
$start_date = date('d-M-Y');
$end_date = date('d-M-Y', strtotime('+1 years'));
$subscription_range = $start_date." to ".$end_date;
$config['subscription_date'] = $subscription_range ;
//prefix  
$config['FinQuest_invoice_no_prefix'] = 'PFQ/'.$fromyear.'-'.$toyear.'/';//prefix for duplicate id card 
$config['FinQuest_invoice_no_prefix_jammu'] = 'PFQJK/'.$fromyear.$toyear.'/';
#-------end Finquest-----------#
#-------JBIMS Registration --------------#
$config['JBIMS_service_code'] = '999293'; 
$config['JBIMS_invoice_no_prefix'] = 'JBIMS/'.$yearnow.'-'.$yearnext.'/';
$config['JBIMS_cgst_rate'] = '9';
$config['JBIMS_sgst_rate'] = '9';
$config['JBIMS_igst_rate'] = '18';
//------Full Fee
$config['JBIMS_full_fee'] = '25000'; 
$config['JBIMS_full_course_fee'] = '25000'; 
$config['JBIMS_full_travel_fee'] = '0'; 
$config['JBIMS_full_sgst_amt'] = '2250';
$config['JBIMS_full_cgst_amt'] = '2250'; 
$config['JBIMS_full_cs_total'] = '29500'; 
$config['JBIMS_full_GST_amt'] = '4500'; 
$config['JBIMS_full_igst_amt'] = '4500';
$config['JBIMS_full_igst_tot'] = '29500';
//------First Instalment
$config['JBIMS_first_fee'] = '25000'; 
$config['JBIMS_first_course_fee'] = '25000'; 
$config['JBIMS_first_travel_fee'] = '0'; 
$config['JBIMS_first_sgst_amt'] = '2250';
$config['JBIMS_first_cgst_amt'] = '2250'; 
$config['JBIMS_first_GST_amt'] = '4500'; 
$config['JBIMS_first_cs_total'] = '29500'; 
$config['JBIMS_first_igst_amt'] = '4500';
$config['JBIMS_first_igst_tot'] = '29500';
//------Second Instalment
$config['JBIMS_second_fee'] = '50000'; 
$config['JBIMS_second_course_fee'] = '50000'; 
$config['JBIMS_second_travel_fee'] = '0'; 
$config['JBIMS_second_sgst_amt'] = '4500';
$config['JBIMS_second_cgst_amt'] = '4500'; 
$config['JBIMS_second_cs_total'] = '59000';
$config['JBIMS_second_GST_amt'] = '9000';
$config['JBIMS_second_igst_amt'] = '9000';
$config['JBIMS_second_igst_tot'] = '59000';
//------Third Instalment
$config['JBIMS_third_fee'] = '50000'; 
$config['JBIMS_third_course_fee'] = '50000'; 
$config['JBIMS_third_travel_fee'] = '0'; 
$config['JBIMS_third_sgst_amt'] = '4500';
$config['JBIMS_third_cgst_amt'] = '4500'; 
$config['JBIMS_third_cs_total'] = '59000';
$config['JBIMS_third_GST_amt'] = '9000';
$config['JBIMS_third_igst_amt'] = '9000';
$config['JBIMS_third_igst_tot'] = '59000';
#-------end JBIMS Registration --------------#
#-------XLRI Registration --------------#
$config['XLRI_service_code'] = '999293'; 
$config['XLRI_invoice_no_prefix'] = 'XLRI/'.$yearnow.'-'.$yearnext.'/';
$config['XLRI_cgst_rate'] = '9';
$config['XLRI_sgst_rate'] = '9';
$config['XLRI_igst_rate'] = '18';
//------Full Fee
$config['XLRI_full_fee'] = '40000'; 
$config['XLRI_full_course_fee'] = '40000'; 
$config['XLRI_full_travel_fee'] = '0'; 
$config['XLRI_full_sgst_amt'] = '3600';
$config['XLRI_full_cgst_amt'] = '3600'; 
$config['XLRI_full_cs_total'] = '47200'; 
$config['XLRI_full_GST_amt'] = '7200'; 
$config['XLRI_full_igst_amt'] = '7200';
$config['XLRI_full_igst_tot'] = '47200';
//------First Instalment
$config['XLRI_first_fee'] = '25000'; 
$config['XLRI_first_course_fee'] = '25000'; 
$config['XLRI_first_travel_fee'] = '0'; 
$config['XLRI_first_sgst_amt'] = '2250';
$config['XLRI_first_cgst_amt'] = '2250'; 
$config['XLRI_first_GST_amt'] = '4500'; 
$config['XLRI_first_cs_total'] = '29500'; 
$config['XLRI_first_igst_amt'] = '4500';
$config['XLRI_first_igst_tot'] = '29500';
//------Second Instalment
$config['XLRI_second_fee'] = '50000'; 
$config['XLRI_second_course_fee'] = '50000'; 
$config['XLRI_second_travel_fee'] = '0'; 
$config['XLRI_second_sgst_amt'] = '4500';
$config['XLRI_second_cgst_amt'] = '4500'; 
$config['XLRI_second_cs_total'] = '59000';
$config['XLRI_second_GST_amt'] = '9000';
$config['XLRI_second_igst_amt'] = '9000';
$config['XLRI_second_igst_tot'] = '59000';
//------Third Instalment
$config['XLRI_third_fee'] = '50000'; 
$config['XLRI_third_course_fee'] = '50000'; 
$config['XLRI_third_travel_fee'] = '0'; 
$config['XLRI_third_sgst_amt'] = '4500';
$config['XLRI_third_cgst_amt'] = '4500'; 
$config['XLRI_third_cs_total'] = '59000';
$config['XLRI_third_GST_amt'] = '9000';
$config['XLRI_third_igst_amt'] = '9000';
$config['XLRI_third_igst_tot'] = '59000';
#-------end XLRI Registration --------------#
#-------Contact Classes ----------#
//CO
$config['Contact_classes_invoice_no_prefix_CO'] = 'TUCO/'.$fromyear.'-'.$toyear.'/';//prefix for duplicate id card 
$config['Contact_classes_invoice_no_prefix_jammu_CO'] = 'TUCOJK/'.$fromyear.$toyear.'/';
//NZ
$config['Contact_classes_invoice_no_prefix_NZ'] = 'TUNZ/'.$fromyear.'-'.$toyear.'/';//prefix for duplicate id card 
$config['Contact_classes_invoice_no_prefix_jammu_NZ'] = 'TUNZJK/'.$fromyear.$toyear.'/';
//SZ
$config['Contact_classes_invoice_no_prefix_SZ'] = 'TUSZ/'.$fromyear.'-'.$toyear.'/';//prefix for duplicate id card 
$config['Contact_classes_invoice_no_prefix_jammu_SZ'] = 'TUSZJK/'.$fromyear.$toyear.'/';
//EZ
$config['Contact_classes_invoice_no_prefix_EZ'] = 'TUEZ/'.$fromyear.'-'.$toyear.'/';//prefix for duplicate id card 
$config['Contact_classes_invoice_no_prefix_jammu_EZ'] = 'TUEZJK/'.$fromyear.$toyear.'/';
$config['contact_classes_cgst_rate'] = '9';
$config['contact_classes_sgst_rate'] = '9';
$config['contact_classes_igst_rate'] = '18';
$config['contact_classes_service_code'] = '999293'; 	
#-------end Contact Classes -----------#
// Renewal Member Registration Set GST rate
$config['renewal_cgst_rate'] = '9';
$config['renewal_sgst_rate'] = '9';
$config['renewal_igst_rate'] = '18';
$config['renewal_fee_amt'] = '1500';
$config['renewal_sgst_amt'] = '135';
$config['renewal_cgst_amt'] = '135';
$config['renewal_igst_amt'] = '270';
$config['renewal_cs_total'] = '1770';
$config['renewal_igst_total'] = '1770';
// Service Codes
$config['renewal_member_service_code'] = '999599'; 	// Renewal Member 
// Renewal Member Registration set GST Invoice Number Format
//$config['renewal_mem_invoice_no_prefix'] = 'IIBF/MEMRENW/'.$yearnow.'-'.$yearnext.'/';
//$config['renewal_mem_invoice_no_prefix_jammu'] = 'IIBF/MEMRENW/'.$yearnow.'-'.$yearnext.'/J&K/';
$config['renewal_mem_invoice_no_prefix'] = 'MRN/'.$yearnow.'-'.$yearnext.'/';
$config['renewal_mem_invoice_no_prefix_jammu'] = 'MRN/JK/'.$yearnow.$yearnext.'/';
// for Bankquest
//$bv_from = date("y");
//$bv_to   = date("y")+1;
$bv_from = '22';
$bv_to   = '23';
$config['bankquest_fee_amt'] = '160';
$config['bankquest_service_code'] = '4902';
$config['bankquest_no_prefix'] = 'PBQ/'.$bv_from.'-'.$bv_to.'/';
//fot iibf vision
$config['vision_fee_amt'] = '40';
$config['vision_service_code'] = '4902';
$config['vision_no_prefix'] = 'PVI/'.$bv_from.'-'.$bv_to.'/';
// chartered Set GST rate
$config['chartered_cgst_rate'] = '9';
$config['chartered_sgst_rate'] = '9';
$config['chartered_igst_rate'] = '18';
$config['chartered_service_code'] = '999294'; 	// chartered Member 
// Blended Set GST rate
$config['blended_cgst_rate'] = '9';
$config['blended_sgst_rate'] = '9';
$config['blended_igst_rate'] = '18';
$config['blended_service_code'] = '999293'; 	// Blended Member 
// Blended set GST Invoice Number Format
$config['blended_invoice_TCO_prefix'] = 'TCO/'.$yearnow.$yearnext.'/';
$config['blended_invoice_TNZ_prefix'] = 'TNZ/'.$yearnow.$yearnext.'/';
$config['blended_invoice_TSZ_prefix'] = 'TSZ/'.$yearnow.$yearnext.'/';
$config['blended_invoice_TEZ_prefix'] = 'TEZ/'.$yearnow.$yearnext.'/';
#------DRA Institute ------------------#
$config['DRA_inst_service_code'] = '999799'; 
$config['DRA_invoice_no_prefix'] = 'DRAACC/'.$yearnow.'-'.$yearnext.'/';
$config['DRA_invoice_no_prefix_jammu'] = 'DRAACCJK/'.$yearnow.''.$yearnext.'/';
$config['DRA_inst_cgst_rate'] = '9';
$config['DRA_inst_sgst_rate'] = '9';
$config['DRA_inst_igst_rate'] = '18';
$config['DRA_regular_apply_fee'] = '9000'; 
$config['DRA_regular_sgst_amt'] = '810'; 
$config['DRA_regular_cgst_amt'] = '810'; 
$config['DRA_regular_cs_total'] = '10620'; 
$config['DRA_regular_igst_amt'] = '1620';
$config['DRA_regular_igst_tot'] = '10620';
$config['DRA_mobile_apply_fee'] = '3000'; 
$config['DRA_mobile_sgst_amt'] = '270'; 
$config['DRA_mobile_cgst_amt'] = '270';
$config['DRA_mobile_cs_total'] = '3540';
$config['DRA_mobile_igst_amt'] = '540';
$config['DRA_mobile_igst_tot'] = '3540';
// added by Manoj for renew regular fee
$config['DRA_regular_renew_fee'] = '5000'; 
$config['DRA_regular_renew_sgst_amt'] = '450';
$config['DRA_regular_renew_cgst_amt'] = '450'; 
$config['DRA_regular_renew_cs_total'] = '5900';
$config['DRA_regular_renew_igst_amt'] = '900';
$config['DRA_regular_renew_igst_tot'] = '5900';
$config['DRA_agency_renew_invoice_no_prefix'] = 'DRN/'.$yearnow.'-'.$yearnext.'/';
#------DRA Institute ------------------#
#-------Amp Registration --------------#
//Amp amount self spensor
$config['amp_service_code'] = '999293'; 
$config['amp_invoice_no_prefix'] = 'AMP/'.$yearnow.'-'.$yearnext.'/';
$config['amp_cgst_rate'] = '9';
$config['amp_sgst_rate'] = '9';
$config['amp_igst_rate'] = '18';

//------Full Fee

$config['amp_full_fee'] = '159300'; 
$config['amp_full_course_fee'] = '135000'; 
$config['amp_full_travel_fee'] = '0'; 
$config['amp_full_sgst_amt'] = '12150';
$config['amp_full_cgst_amt'] = '12150'; 
$config['amp_full_cs_total'] = '159300'; 
$config['amp_full_GST_amt'] = '24300'; 
$config['amp_full_igst_amt'] = '24300';
$config['amp_full_igst_tot'] = '159300';

//------First Instalment
$config['amp_first_fee'] = '35000'; 
$config['amp_first_course_fee'] = '35000'; 
$config['amp_first_travel_fee'] = '0'; 
$config['amp_first_sgst_amt'] = '3150';
$config['amp_first_cgst_amt'] = '3150'; 
$config['amp_first_GST_amt'] = '6300'; 
$config['amp_first_cs_total'] = '41300'; 
$config['amp_first_igst_amt'] = '6300';
$config['amp_first_igst_tot'] = '41300';

//------Second Instalment
$config['amp_second_fee'] = '50000'; 
$config['amp_second_course_fee'] = '50000'; 
$config['amp_second_travel_fee'] = '0'; 
$config['amp_second_sgst_amt'] = '4500';
$config['amp_second_cgst_amt'] = '4500'; 
$config['amp_second_cs_total'] = '59000';
$config['amp_second_GST_amt'] = '9000';
$config['amp_second_igst_amt'] = '9000';
$config['amp_second_igst_tot'] = '59000';

//------Third Instalment
$config['amp_third_fee'] = '50000'; 
$config['amp_third_course_fee'] = '50000'; 
$config['amp_third_travel_fee'] = '0'; 
$config['amp_third_sgst_amt'] = '4500';
$config['amp_third_cgst_amt'] = '4500'; 
$config['amp_third_cs_total'] = '59000';
$config['amp_third_GST_amt'] = '9000';
$config['amp_third_igst_amt'] = '9000';
$config['amp_third_igst_tot'] = '59000';
  
#-------end Amp Registration --------------#
#---------------| GST Recovery Module |--------------#
$config['gst_recovery_prefix'] = 'DN/'.$yearnow.'-'.$yearnext.'/';
#---------------| GST Recovery Module Close|--------------#
#########################
$config['e-learn-msg']='<p>At present Institute is providing e-learning for the following examinations:</p>
<ol class="elearn">
  <li> JAIIB</li>
  <li> CAIIB</li>
  <li> DB&amp;F</li>
  <li> Diploma in Treasury, Investment &amp; Risk Management</li>
  <li> Customer Service &amp; Banking Codes &amp; Standards </li>
  <li> Anti-Money Laundering/Know Your Customer</li>
  <li> Risk in Financial Services</li>
</ol>
<p>E-learning will be activated within THREE working days after registration for the above mentioned examinations.</p>
';
#########################