<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2025-07-04 13:06:49 --> Severity: Warning --> imagepng(uploads/bulk_proforma_examinvoice/bulk_74.jpg): failed to open stream: No such file or directory /home/supp0rttest/public_html/staging/application/helpers/bulk_proforma_invoice_helper.php 226
ERROR - 2025-07-04 13:06:49 --> Severity: Warning --> imagepng(uploads/bulk_proforma_examinvoice/bulk_74.jpg): failed to open stream: No such file or directory /home/supp0rttest/public_html/staging/application/helpers/bulk_proforma_invoice_helper.php 230
ERROR - 2025-07-04 14:33:50 --> Severity: Warning --> imagepng(uploads/bulk_proforma_examinvoice/bulk_75.jpg): failed to open stream: No such file or directory /home/supp0rttest/public_html/staging/application/helpers/bulk_proforma_invoice_helper.php 226
ERROR - 2025-07-04 14:33:50 --> Severity: Warning --> imagepng(uploads/bulk_proforma_examinvoice/bulk_75.jpg): failed to open stream: No such file or directory /home/supp0rttest/public_html/staging/application/helpers/bulk_proforma_invoice_helper.php 230
ERROR - 2025-07-04 17:15:19 --> Query error: Column 'exam_ids' cannot be null - Invalid query: INSERT INTO `iibfbcbf_payment_transaction` (`exam_ids`, `gateway`, `amount`, `date`, `description`, `payment_mode`, `status`, `pg_flag`) VALUES (NULL, '2', NULL, '2025-07-04 17:15:19', 'Bulk test Payment', 'Bulk', 2, 'BC')
ERROR - 2025-07-04 17:15:19 --> Query error: Column 'member_no' cannot be null - Invalid query: INSERT INTO `exam_invoice` (`pay_txn_id`, `receipt_no`, `member_no`, `state_of_center`, `app_type`, `service_code`, `qty`, `state_code`, `state_name`, `tax_type`, `fee_amt`, `cgst_rate`, `cgst_amt`, `sgst_rate`, `sgst_amt`, `igst_rate`, `igst_amt`, `cs_total`, `igst_total`, `gstin_no`, `exempt`, `created_on`) VALUES (0, '', NULL, NULL, 'R', '999599', '1', NULL, NULL, 'Inter', 1, '', '', '', '', '18', '270', '', NULL, '', NULL, '2025-07-04 17:15:19')
ERROR - 2025-07-04 17:15:46 --> 404 Page Not Found: Test_payment_page/favicon.ico
ERROR - 2025-07-04 17:41:49 --> 404 Page Not Found: Assets/js
ERROR - 2025-07-04 18:45:40 --> Severity: Warning --> imagepng(uploads/bulk_proforma_examinvoice/bulk_76.jpg): failed to open stream: No such file or directory /home/supp0rttest/public_html/staging/application/helpers/bulk_proforma_invoice_helper.php 226
ERROR - 2025-07-04 18:45:40 --> Severity: Warning --> imagepng(uploads/bulk_proforma_examinvoice/bulk_76.jpg): failed to open stream: No such file or directory /home/supp0rttest/public_html/staging/application/helpers/bulk_proforma_invoice_helper.php 230
ERROR - 2025-07-04 18:51:36 --> Severity: Warning --> array_unique() expects parameter 1 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/bulk/BulkTransaction.php 216
ERROR - 2025-07-04 18:51:36 --> Severity: Warning --> implode(): Invalid arguments passed /home/supp0rttest/public_html/staging/application/controllers/bulk/BulkTransaction.php 216
ERROR - 2025-07-04 18:59:48 --> Severity: Warning --> array_unique() expects parameter 1 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/bulk/BulkTransaction.php 216
ERROR - 2025-07-04 18:59:48 --> Severity: Warning --> implode(): Invalid arguments passed /home/supp0rttest/public_html/staging/application/controllers/bulk/BulkTransaction.php 216
ERROR - 2025-07-04 19:09:56 --> Severity: 4096 --> Object of class CI_Loader could not be converted to string /home/supp0rttest/public_html/staging/application/views/jdadmitcardpdf.php 1
