<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2025-02-09 11:26:03 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2025-02-09 13:33:12 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('8', 'In_charge', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:25 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('17', 'In_charge', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:26 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('8', 'In_charge', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:28 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('15', 'In_charge', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:29 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('16', 'In_charge', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:31 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'Faculty_Member', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:32 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_IT', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:35 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'Faculty_Member', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:36 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'Faculty_Member', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:41:37 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'Faculty_Member', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:50:05 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_IT', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-02-09 13:55:35 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('15', 'In_charge', '10.11.38.105', 'UnKnown||UnKnown', NULL)
