<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-12-05 18:09:57 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'asc LIMIT 0, 10' at line 45 - Invalid query: SELECT acb.batch_id, am1.agency_name, CONCAT(cm.centre_name," (",cm1.city_name,")") AS DispCentreName, acb.batch_code, IF(acb.batch_type=1, "Basic", IF(acb.batch_type=2, "Advanced", "")) AS DispBatchType, acb.batch_start_date, acb.batch_end_date, IF(acb.batch_status = 0, "In Review", IF(acb.batch_status = 1, "Final Review", IF(acb.batch_status = 2, "Batch Error", IF(acb.batch_status = 3, "Go Ahead", IF(acb.batch_status = 4, "Hold", IF(acb.batch_status = 5, "Rejected", IF(acb.batch_status = 6, "Re-Submitted", "Cancelled"))))))) AS DispBatchStatus, COUNT(DISTINCT CASE WHEN bc.hold_release_status = "3" THEN bc.candidate_id END) AS total_release_candidate, COUNT(DISTINCT CASE WHEN bc.hold_release_status = "2" OR bc.hold_release_status = "1" THEN bc.candidate_id END) AS total_hold_candidate, im.inspector_name, COUNT(bi.inspection_id) AS inspection_count, IF(bi.inspection_start_time != "0000-00-00 00:00:00", SUM(TIMESTAMPDIFF(MINUTE, bi.inspection_start_time, bi.created_on)),"0") AS total_inspection_time_minutes, (
      SUM(CASE WHEN bi.teaching_quality_interaction_with_candidates = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_quality_softskill_session = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.candidates_attentiveness = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.attitude_behaviour = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_interaction_with_faculty = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_response_to_queries = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_effectiveness = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.curriculum_covered = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_delivery = "Poor" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_coordination = "Poor" THEN 1 ELSE 0 END)
  ) AS total_poor_counts, (
      SUM(CASE WHEN bi.teaching_quality_interaction_with_candidates = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_quality_softskill_session = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.candidates_attentiveness = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.attitude_behaviour = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_interaction_with_faculty = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_response_to_queries = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_effectiveness = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.curriculum_covered = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_delivery = "Average" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_coordination = "Average" THEN 1 ELSE 0 END)
  ) AS total_average_counts, (
      SUM(CASE WHEN bi.teaching_quality_interaction_with_candidates = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_quality_softskill_session = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.candidates_attentiveness = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.attitude_behaviour = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_interaction_with_faculty = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_response_to_queries = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_effectiveness = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.curriculum_covered = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_delivery = "Good" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_coordination = "Good" THEN 1 ELSE 0 END)
  ) AS total_good_counts, (
      SUM(CASE WHEN bi.teaching_quality_interaction_with_candidates = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_quality_softskill_session = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.candidates_attentiveness = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.attitude_behaviour = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_interaction_with_faculty = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.learning_quality_response_to_queries = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.teaching_effectiveness = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.curriculum_covered = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_delivery = "Excellent" THEN 1 ELSE 0 END) +
      SUM(CASE WHEN bi.overall_compliance_training_coordination = "Excellent" THEN 1 ELSE 0 END)
  ) AS total_excellent_counts, CONCAT(TIME_FORMAT(acb.batch_daily_start_time, "%h:%i %p"), " To ", TIME_FORMAT(acb.batch_daily_end_time, "%h:%i %p")) AS BatchTime, acb.total_candidates, GROUP_CONCAT( DISTINCT im.inspector_name SEPARATOR ", ") AS all_assign_inspectors, acb.batch_status, acb.centre_id, acb.batch_type, acb.batch_online_offline_flag, acb.agency_id FROM iibfbcbf_agency_centre_batch acb  LEFT JOIN iibfbcbf_centre_master cm ON cm.centre_id = acb.centre_id LEFT JOIN city_master cm1 ON cm1.id = cm.centre_city LEFT JOIN iibfbcbf_agency_master am1 ON am1.agency_id = acb.agency_id LEFT JOIN iibfbcbf_batch_inspection bi ON bi.batch_id = acb.batch_id LEFT JOIN iibfbcbf_inspector_master im ON im.inspector_id = bi.inspector_id LEFT JOIN iibfbcbf_batch_candidates bc ON bc.batch_id = acb.batch_id WHERE acb.is_deleted = 0   Group By acb.batch_id ORDER BY COUNT(DISTINCT C asc LIMIT 0, 10 
ERROR - 2024-12-05 18:09:57 --> Severity: Error --> Call to a member function result_array() on boolean /home/supp0rttest/public_html/staging/application/controllers/iibfbcbf/admin/Reports.php 988
ERROR - 2024-12-05 18:52:36 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'asc LIMIT 0, 10' at line 1 - Invalid query: SELECT "", acb.batch_id, am1.agency_name, CONCAT(cm.centre_name," (",cm1.city_name,")") AS DispCentreName, acb.batch_code, acb.centre_batch_id, IF(acb.batch_type=1, "Basic", IF(acb.batch_type=2, "Advanced", "")) AS DispBatchType, acb.batch_start_date, acb.batch_end_date, CONCAT(TIME_FORMAT(acb.batch_daily_start_time, "%h:%i %p"), " To ", TIME_FORMAT(acb.batch_daily_end_time, "%h:%i %p")) AS BatchTime, acb.total_candidates, DATE_FORMAT(acb.created_on, "%Y-%m-%d %H:%i %p") AS batch_created_on, IF(acb.batch_status = 0, "In Review", IF(acb.batch_status = 1, "Final Review", IF(acb.batch_status = 2, "Batch Error", IF(acb.batch_status = 3, "Go Ahead", IF(acb.batch_status = 4, "Hold", IF(acb.batch_status = 5, "Rejected", IF(acb.batch_status = 6, "Re-Submitted", "Cancelled"))))))) AS DispBatchStatus, COUNT(DISTINCT CASE WHEN bc.re_attempt > "0" THEN bc.candidate_id END) AS no_of_candidates_applied_for_exam, acb.batch_status, acb.centre_id, acb.batch_type, acb.batch_online_offline_flag, acb.agency_id FROM iibfbcbf_agency_centre_batch acb  LEFT JOIN iibfbcbf_centre_master cm ON cm.centre_id = acb.centre_id LEFT JOIN city_master cm1 ON cm1.id = cm.centre_city LEFT JOIN iibfbcbf_agency_master am1 ON am1.agency_id = acb.agency_id LEFT JOIN iibfbcbf_batch_candidates bc ON bc.batch_id = acb.batch_id WHERE acb.is_deleted = 0   Group By acb.batch_id ORDER BY COUNT(DISTINCT C asc LIMIT 0, 10 
ERROR - 2024-12-05 18:52:36 --> Severity: Error --> Call to a member function result_array() on boolean /home/supp0rttest/public_html/staging/application/controllers/iibfbcbf/admin/Reports.php 2103
ERROR - 2024-12-05 18:53:16 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'asc LIMIT 0, 10' at line 1 - Invalid query: SELECT "", acb.batch_id, am1.agency_name, CONCAT(cm.centre_name," (",cm1.city_name,")") AS DispCentreName, acb.batch_code, acb.centre_batch_id, IF(acb.batch_type=1, "Basic", IF(acb.batch_type=2, "Advanced", "")) AS DispBatchType, acb.batch_start_date, acb.batch_end_date, CONCAT(TIME_FORMAT(acb.batch_daily_start_time, "%h:%i %p"), " To ", TIME_FORMAT(acb.batch_daily_end_time, "%h:%i %p")) AS BatchTime, acb.total_candidates, DATE_FORMAT(acb.created_on, "%Y-%m-%d %H:%i %p") AS batch_created_on, IF(acb.batch_status = 0, "In Review", IF(acb.batch_status = 1, "Final Review", IF(acb.batch_status = 2, "Batch Error", IF(acb.batch_status = 3, "Go Ahead", IF(acb.batch_status = 4, "Hold", IF(acb.batch_status = 5, "Rejected", IF(acb.batch_status = 6, "Re-Submitted", "Cancelled"))))))) AS DispBatchStatus, COUNT(DISTINCT CASE WHEN bc.re_attempt > "0" THEN bc.candidate_id END) AS no_of_candidates_applied_for_exam, acb.batch_status, acb.centre_id, acb.batch_type, acb.batch_online_offline_flag, acb.agency_id FROM iibfbcbf_agency_centre_batch acb  LEFT JOIN iibfbcbf_centre_master cm ON cm.centre_id = acb.centre_id LEFT JOIN city_master cm1 ON cm1.id = cm.centre_city LEFT JOIN iibfbcbf_agency_master am1 ON am1.agency_id = acb.agency_id LEFT JOIN iibfbcbf_batch_candidates bc ON bc.batch_id = acb.batch_id WHERE acb.is_deleted = 0   Group By acb.batch_id ORDER BY COUNT(DISTINCT C asc LIMIT 0, 10 
ERROR - 2024-12-05 18:53:16 --> Severity: Error --> Call to a member function result_array() on boolean /home/supp0rttest/public_html/staging/application/controllers/iibfbcbf/admin/Reports.php 2103
ERROR - 2024-12-05 18:57:09 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'asc LIMIT 0, 10' at line 1 - Invalid query: SELECT "", acb.batch_id, am1.agency_name, CONCAT(cm.centre_name," (",cm1.city_name,")") AS DispCentreName, acb.batch_code, IF(acb.batch_type=1, "Basic", IF(acb.batch_type=2, "Advanced", "")) AS DispBatchType, COUNT(DISTINCT CASE WHEN bc.is_deleted = "0" AND acb.batch_status = "3" THEN bc.candidate_id END) AS tot_candiadtes_registered_for_training, COUNT(DISTINCT CASE WHEN bc.re_attempt = "0" AND bc.hold_release_status = "3" AND DATE_FORMAT(DATE_ADD(acb.batch_end_date, INTERVAL 0 DAY), "%Y-%m-%d") < CURDATE() AND CURDATE() <= DATE_FORMAT(DATE_ADD(acb.batch_end_date, INTERVAL 270 DAY), "%Y-%m-%d") THEN bc.candidate_id END) AS no_of_candidates_eligible_for_exam, COUNT(DISTINCT CASE WHEN bc.re_attempt > "0" THEN bc.candidate_id END) AS no_of_candidates_applied_for_exam, acb.batch_status, acb.centre_id, acb.batch_type FROM iibfbcbf_agency_centre_batch acb  LEFT JOIN iibfbcbf_centre_master cm ON cm.centre_id = acb.centre_id LEFT JOIN city_master cm1 ON cm1.id = cm.centre_city LEFT JOIN iibfbcbf_agency_master am1 ON am1.agency_id = acb.agency_id LEFT JOIN iibfbcbf_batch_candidates bc ON bc.batch_id = acb.batch_id WHERE acb.is_deleted = 0   Group By acb.batch_id ORDER BY COUNT(DISTINCT C asc LIMIT 0, 10 
ERROR - 2024-12-05 18:57:09 --> Severity: Error --> Call to a member function result_array() on boolean /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3389
