<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2025-10-20 00:03:19 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'Rupali', '', 'Najan', 'Narayan', '1992-10-15', 'female', 'rupali.najan@esds.co.in', 'Married', '7127676117', '9620851846', 'AG456566HY', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'IPSAM NON QUAERAT CU', 'OMNIS SUNT LABORE N', 'BANGALORE', 'MAH', '422009', '', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'IPSAM NON QUAERAT CU', 'OMNIS SUNT LABORE N', 'BANGALORE', 'MAH', '422009', '7620851847', '0', 'Finance', NULL, NULL, 'test', 'test', '2025-06', '2025-10', '', '', '', '', '', '', '2024', '876543', 'hindi', 'Read,Write', '', '', '', '', '', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8727676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '9827676117', 'photo_176085508859.jpg', 'sign_176085508843.jpg', '', '', 'Yes', 'Yes', '', 'test', '2025-10-15', '2025-10-20 00:03:19', '3', '', '', '', '', '', NULL, '', '', '', NULL, '', '', '1970-01-01', '1970-01-01')
ERROR - 2025-10-20 02:48:57 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-04-03', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '', '', '', '2024', '876543', 'hindi', 'Read,Write,Speak', 'test', 'Read', 'test', 'Read', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176090872778.jpg', 'sign_176090872725.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-08', '2025-10-20 02:48:57', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-07', '2025-10-17')
ERROR - 2025-10-20 03:06:34 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-10-14', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '', '', '', '2020', '876543', 'hindi', 'Read,Write,Speak', 'test', 'Read', 'test', 'Read', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176090976039.jpg', 'sign_176090976042.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-08', '2025-10-20 03:06:34', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-01', '2025-10-08')
ERROR - 2025-10-20 03:11:14 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-10-14', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '', '', '', '2020', '876543', 'hindi', 'Read,Write,Speak', 'test', 'Read', 'test', 'Read', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176090976039.jpg', 'sign_176090976042.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-08', '2025-10-20 03:11:14', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-01', '2025-10-08')
ERROR - 2025-10-20 03:29:28 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-10-14', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '76', '', '1', '2020', '876543', 'hindi', 'Read,Write', 'test', 'Write', 'test', 'Speak', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176091113413.jpg', 'sign_176091113462.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-14', '2025-10-20 03:29:28', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-01', '2025-10-15')
ERROR - 2025-10-20 04:32:25 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2025-10-20 11:12:06 --> 404 Page Not Found: Envbak/index
ERROR - 2025-10-20 11:12:07 --> 404 Page Not Found: Envcrt/index
ERROR - 2025-10-20 11:12:09 --> 404 Page Not Found: Envdev/index
ERROR - 2025-10-20 11:12:10 --> 404 Page Not Found: Envgcp/index
ERROR - 2025-10-20 11:12:11 --> 404 Page Not Found: Envkey/index
ERROR - 2025-10-20 11:12:13 --> 404 Page Not Found: Envlog/index
ERROR - 2025-10-20 11:12:14 --> 404 Page Not Found: Envold/index
ERROR - 2025-10-20 11:12:16 --> 404 Page Not Found: Envpem/index
ERROR - 2025-10-20 11:12:17 --> 404 Page Not Found: Envtmp/index
ERROR - 2025-10-20 11:12:18 --> 404 Page Not Found: Envuat/index
ERROR - 2025-10-20 11:12:20 --> 404 Page Not Found: Api/.env
ERROR - 2025-10-20 12:11:11 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-06-06', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '76', '', '1', '2024', '876543', 'hindi', 'Read,Write', 'test', 'Write', 'test', 'Speak', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176094246327.jpg', 'sign_176094246375.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-08', '2025-10-20 12:11:11', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-07', '2025-10-16')
ERROR - 2025-10-20 12:20:21 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-06-06', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '76', '', '1', '2024', '876543', 'hindi', 'Read,Write', 'test', 'Write', 'test', 'Speak', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176094246327.jpg', 'sign_176094246375.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-08', '2025-10-20 12:20:21', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-07', '2025-10-16')
ERROR - 2025-10-20 12:24:06 --> Query error: Column 'ess_pg_stream_subject' cannot be null - Invalid query: INSERT INTO `careers_registration` (`sel_namesub`, `firstname`, `middlename`, `lastname`, `father_husband_name`, `dateofbirth`, `gender`, `email`, `marital_status`, `mobile`, `alternate_mobile`, `pan_no`, `aadhar_card_no`, `addressline1`, `addressline2`, `addressline3`, `addressline4`, `district`, `city`, `state`, `pincode`, `contact_number`, `addressline1_pr`, `addressline2_pr`, `addressline3_pr`, `addressline4_pr`, `district_pr`, `city_pr`, `state_pr`, `pincode_pr`, `contact_number_pr`, `exam_center`, `ess_course_name`, `ess_pg_stream_subject`, `ess_subject`, `ess_college_name`, `ess_university`, `ess_from_date`, `ess_to_date`, `ess_degree_completion_date`, `ess_aggregate_marks_obtained`, `ess_aggregate_max_marks`, `ess_percentage`, `ess_grade_marks`, `ess_class`, `year_of_passing`, `membership_number`, `languages_known`, `languages_option`, `languages_known1`, `languages_option1`, `languages_known2`, `languages_option2`, `extracurricular`, `hobbies`, `achievements`, `refname_one`, `refaddressline_one`, `reforganisation_one`, `refdesignation_one`, `refemail_one`, `refmobile_one`, `refname_two`, `refaddressline_two`, `reforganisation_two`, `refdesignation_two`, `refemail_two`, `refmobile_two`, `scannedphoto`, `scannedsignaturephoto`, `declaration1`, `declaration_note`, `declaration2`, `declaration3`, `comment`, `place`, `submit_date`, `createdon`, `position_id`, `ph_d`, `phd_course`, `phd_university`, `publication_of_books`, `publication_of_articles`, `area_of_specialization`, `earliest_date_of_joining`, `suitable_of_the_post_of_CEO`, `exp_in_bank`, `exp_in_functional_area`, `deputy_subject`, `subject_handled`, `exp_faculty_from_date`, `exp_faculty_to_date`) VALUES ('Mrs.', 'RUPALI', 'EDAN', 'NAJAN', 'Narayan', '1997-06-06', 'female', 'rupali.najan@esds.co.in', 'Married', '7620851847', '8727676117', 'AG456566HE', '987654321234', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', 'R K Nashik', 'NEAR MALVIYA NAGAR', 'NEW DELHI 110017', 'POONCH', 'POONCH', 'BANGALORE', 'MAH', '422009', '7820851849', '0', 'Economics', NULL, NULL, 'test', 'test', '2025-02', '2025-06', '', '67', '67', '76', '', '1', '2024', '876543', 'hindi', 'Read,Write', 'test', 'Write', 'test', 'Speak', 'test', 'test', 'test', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '8127676117', 'RUPALI  NAJAN', 'test', 'test', 'test', 'pooja.mane@eeej.cc', '7127676117', 'photo_176094246327.jpg', 'sign_176094246375.jpg', '', '', 'Yes', 'Yes', 'test', 'test', '2025-10-08', '2025-10-20 12:24:06', '3', '', '', '', 'test', '', NULL, '', '', 'test', 'test', '', 'test', '2025-10-07', '2025-10-16')
ERROR - 2025-10-20 14:44:27 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12453
ERROR - 2025-10-20 14:44:31 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12453
ERROR - 2025-10-20 14:44:45 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12453
ERROR - 2025-10-20 14:44:52 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12453
ERROR - 2025-10-20 14:45:36 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12453
ERROR - 2025-10-20 14:45:42 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12453
ERROR - 2025-10-20 14:46:23 --> Severity: Compile Error --> Cannot redeclare Careers::generate_captcha_ajax() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12454
ERROR - 2025-10-20 14:49:47 --> Severity: Parsing Error --> syntax error, unexpected '$this' (T_VARIABLE), expecting function (T_FUNCTION) /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12457
ERROR - 2025-10-20 15:12:10 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 15:12:24 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 15:22:11 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 15:22:11 --> 404 Page Not Found: Careers/generate_captcha_ajax
ERROR - 2025-10-20 15:22:17 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 15:22:18 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 15:22:18 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 15:22:18 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 15:30:03 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 8942
ERROR - 2025-10-20 15:30:05 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 8942
ERROR - 2025-10-20 15:30:06 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 8942
ERROR - 2025-10-20 15:30:47 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 15:31:02 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 15:31:06 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 15:31:21 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 8942
ERROR - 2025-10-20 15:31:35 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 8942
ERROR - 2025-10-20 15:31:55 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 15:57:55 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 16:00:49 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 16:02:07 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 16:03:29 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 16:03:36 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 16:03:36 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 16:03:37 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 16:03:37 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12487
ERROR - 2025-10-20 16:03:43 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 16:04:03 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 16:04:07 --> Severity: Error --> Call to undefined function create_captcha() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12472
ERROR - 2025-10-20 16:19:55 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 16:35:32 --> Severity: Parsing Error --> syntax error, unexpected end of file, expecting function (T_FUNCTION) /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12504
ERROR - 2025-10-20 16:35:35 --> Severity: Parsing Error --> syntax error, unexpected end of file, expecting function (T_FUNCTION) /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12504
ERROR - 2025-10-20 16:44:51 --> Severity: Parsing Error --> syntax error, unexpected end of file, expecting function (T_FUNCTION) /home/supp0rttest/public_html/staging/application/controllers/Careers.php 12509
ERROR - 2025-10-20 17:18:43 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-10-20 20:22:34 --> 404 Page Not Found: Uploads/exam_instruction
