ERROR - 2025-11-14 22:28:32 --> Query error: Unknown column 'Array' in 'field list' - Invalid query: INSERT INTO `career_other_details` (`spouse_name`, `mother_name`, `religion`, `physical_disbaility`, `physical_disbaility_desc`, `name_of_present_organization`, `service_from_date`, `comm_address_of_org`, `curr_designation`, `any_other_details`, `vrs_register_date`, `reason_of_resign`, `exeplary_details`, `whether_in_service`, `exp_faculty_from_date`, `exp_faculty_to_date`, `phd_from_date`, `phd_to_date`, `des_from_date`, `des_to_date`, `careers_id`, `professional_ass`, `cer_qua_name`, `cer_gra_sub`, `cer_college_name`, `cer_university`, `cer_from_date`, `cer_to_date`, `cer_marks_obtained`, `cer_aggregate_max_marks`, `cer_percentage`, `cer_class`, `post_qua_name`, `post_gra_sub`, `post_gra_college_name`, `post_gra_university`, `post_gra_from_date`, `post_gra_to_date`, `post_aggregate_marks_obtained`, `post_gra_aggregate_max_marks`, `post_gra_percentage`, `post_gra_class`) VALUES ('test', 'Kalavati', 'Hindu', 'no', '', 'test', '2025-10-28', 'R K Nashik', 'Operations Officer', 'Branch Operations Management', '', '', '', 'yes', '2025-10-26', '2025-11-11', NULL, NULL, NULL, NULL, 592, 'fsdfsd', '', '', '', '', '', '', '', '', '', '', Array, Array, Array, Array, Array, Array, Array, Array, Array, Array)
ERROR - 2025-11-14 22:28:32 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11096
ERROR - 2025-11-14 22:28:32 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11141
ERROR - 2025-11-14 22:28:32 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11161
ERROR - 2025-11-14 23:35:55 --> Severity: Parsing Error --> syntax error, unexpected '?' /home/supp0rttest/public_html/staging/application/controllers/Careers.php 10932
ERROR - 2025-11-14 23:35:57 --> Severity: Parsing Error --> syntax error, unexpected '?' /home/supp0rttest/public_html/staging/application/controllers/Careers.php 10932
ERROR - 2025-11-14 23:36:07 --> Severity: Parsing Error --> syntax error, unexpected '?' /home/supp0rttest/public_html/staging/application/controllers/Careers.php 10932
ERROR - 2025-11-14 23:36:10 --> Severity: Parsing Error --> syntax error, unexpected '?' /home/supp0rttest/public_html/staging/application/controllers/Careers.php 10932
ERROR - 2025-11-14 23:36:39 --> Severity: Parsing Error --> syntax error, unexpected '?' /home/supp0rttest/public_html/staging/application/controllers/Careers.php 10932
ERROR - 2025-11-14 23:37:38 --> Severity: Parsing Error --> syntax error, unexpected '?' /home/supp0rttest/public_html/staging/application/controllers/Careers.php 10959
ERROR - 2025-11-14 23:49:07 --> Query error: Unknown column 'Array' in 'field list' - Invalid query: INSERT INTO `career_other_details` (`spouse_name`, `mother_name`, `religion`, `physical_disbaility`, `physical_disbaility_desc`, `name_of_present_organization`, `service_from_date`, `comm_address_of_org`, `curr_designation`, `any_other_details`, `vrs_register_date`, `reason_of_resign`, `exeplary_details`, `post_qua_name`, `post_gra_sub`, `post_gra_college_name`, `post_gra_university`, `post_gra_from_date`, `post_gra_to_date`, `post_aggregate_marks_obtained`, `post_gra_aggregate_max_marks`, `post_gra_percentage`, `post_gra_class`, `whether_in_service`, `exp_faculty_from_date`, `exp_faculty_to_date`, `phd_from_date`, `phd_to_date`, `des_from_date`, `des_to_date`, `careers_id`, `professional_ass`, `cer_qua_name`, `cer_gra_sub`, `cer_college_name`, `cer_university`, `cer_from_date`, `cer_to_date`, `cer_marks_obtained`, `cer_aggregate_max_marks`, `cer_percentage`, `cer_class`) VALUES ('test', 'Kalavati', 'Hindu', 'no', '', 'test', '2025-11-03', 'R K Nashik', 'Operations Officer', 'Branch Operations Management', '', '', '', Array, Array, Array, Array, Array, Array, Array, Array, Array, Array, 'yes', '2025-10-26', '2025-11-11', NULL, NULL, NULL, NULL, 593, '', '', '', '', '', '', '', '', '', '', '')
ERROR - 2025-11-14 23:49:07 --> Query error: Unknown column 'careers_id' in 'field list' - Invalid query: INSERT INTO `career_pg_details` (`careers_id`, `post_qua_name`, `post_gra_sub`, `post_gra_college_name`, `post_gra_university`, `post_gra_from_date`, `post_gra_to_date`, `post_aggregate_marks_obtained`, `post_gra_aggregate_max_marks`, `post_gra_percentage`, `post_gra_class`) VALUES (593, 'Banking & Finance', ' Post Graduation sub1', ' Post Graduation college1', ' Post Graduation university 1', '2025-10-27', '2025-11-13', '76', '87', '78', '76')
ERROR - 2025-11-14 23:49:07 --> Query error: Unknown column 'careers_id' in 'field list' - Invalid query: INSERT INTO `career_pg_details` (`careers_id`, `post_qua_name`, `post_gra_sub`, `post_gra_college_name`, `post_gra_university`, `post_gra_from_date`, `post_gra_to_date`, `post_aggregate_marks_obtained`, `post_gra_aggregate_max_marks`, `post_gra_percentage`, `post_gra_class`) VALUES (593, 'Cost and Management Accountant (CMA)', ' Post Graduation sub 2', ' Post Graduation college 2', ' Post Graduation university 2', '2025-10-26', '', '54', '45', '56', '2')
ERROR - 2025-11-14 23:49:07 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11159
ERROR - 2025-11-14 23:49:07 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11204
ERROR - 2025-11-14 23:49:07 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11224
ERROR - 2025-11-14 23:56:36 --> Query error: Unknown column 'Array' in 'field list' - Invalid query: INSERT INTO `career_other_details` (`spouse_name`, `mother_name`, `religion`, `physical_disbaility`, `physical_disbaility_desc`, `name_of_present_organization`, `service_from_date`, `comm_address_of_org`, `curr_designation`, `any_other_details`, `vrs_register_date`, `reason_of_resign`, `exeplary_details`, `post_qua_name`, `post_gra_sub`, `post_gra_college_name`, `post_gra_university`, `post_gra_from_date`, `post_gra_to_date`, `post_aggregate_marks_obtained`, `post_gra_aggregate_max_marks`, `post_gra_percentage`, `post_gra_class`, `whether_in_service`, `exp_faculty_from_date`, `exp_faculty_to_date`, `phd_from_date`, `phd_to_date`, `des_from_date`, `des_to_date`, `careers_id`, `professional_ass`, `cer_qua_name`, `cer_gra_sub`, `cer_college_name`, `cer_university`, `cer_from_date`, `cer_to_date`, `cer_marks_obtained`, `cer_aggregate_max_marks`, `cer_percentage`, `cer_class`) VALUES ('test', 'Kalavati', 'Hindu', 'no', '', 'test', '2025-11-04', 'R K Nashik', 'Operations Officer', 'Branch Operations Management', '', '', '', Array, Array, Array, Array, Array, Array, Array, Array, Array, Array, 'yes', '2025-11-03', '2025-11-11', NULL, NULL, NULL, NULL, 594, '', '', '', '', '', '', '', '', '', '', '')
ERROR - 2025-11-14 23:56:36 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11159
ERROR - 2025-11-14 23:56:36 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11204
ERROR - 2025-11-14 23:56:37 --> Severity: Warning --> Invalid argument supplied for foreach() /home/supp0rttest/public_html/staging/application/controllers/Careers.php 11224
