<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2024-10-28 00:41:44 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 00:41:45 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 00:51:16 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 01:11:44 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 01:11:45 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 03:06:38 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 03:41:47 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 04:43:18 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 05:11:47 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 06:11:48 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 06:41:48 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 07:37:20 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 07:41:49 --> 404 Page Not Found: Uploads/SCRIBE_Guidelines_2022.pdf
ERROR - 2024-10-28 07:41:50 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 08:11:52 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 08:41:49 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 09:11:49 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 09:18:50 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 09:41:51 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 09:52:41 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 10:41:52 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 11:41:32 --> 404 Page Not Found: Uploads/photograph
ERROR - 2024-10-28 11:41:32 --> 404 Page Not Found: Uploads/idproof
ERROR - 2024-10-28 11:41:32 --> 404 Page Not Found: Uploads/declaration
ERROR - 2024-10-28 11:43:42 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO || SIGNATURE || PROOF || DECLARATION ', 'image', '8311473', '510605453', 'User', '8311473', '2024-10-28 11:43:42', '10.11.38.105')
ERROR - 2024-10-28 12:09:21 --> 404 Page Not Found: Uploads/photograph
ERROR - 2024-10-28 12:09:21 --> 404 Page Not Found: Uploads/scansignature
ERROR - 2024-10-28 12:09:21 --> 404 Page Not Found: Uploads/idproof
ERROR - 2024-10-28 12:09:21 --> 404 Page Not Found: Uploads/declaration
ERROR - 2024-10-28 12:10:41 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO || SIGNATURE || PROOF || DECLARATION ', 'image', '8432197', '100004853', 'User', '8432197', '2024-10-28 12:10:41', '10.11.38.105')
ERROR - 2024-10-28 12:12:40 --> 404 Page Not Found: Uploads/scansignature
ERROR - 2024-10-28 12:12:40 --> 404 Page Not Found: Uploads/photograph
ERROR - 2024-10-28 12:12:41 --> 404 Page Not Found: Uploads/idproof
ERROR - 2024-10-28 12:12:41 --> 404 Page Not Found: Uploads/declaration
ERROR - 2024-10-28 12:29:25 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO || SIGNATURE || PROOF || DECLARATION ', 'image', '8430987', '510624196', 'User', '8430987', '2024-10-28 12:29:25', '10.11.38.105')
ERROR - 2024-10-28 12:31:01 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO || SIGNATURE || PROOF || DECLARATION ', 'image', '8432480', '510620176', 'User', '8432480', '2024-10-28 12:31:01', '10.11.38.105')
ERROR - 2024-10-28 12:31:45 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'DECLARATION ', 'image', '8432193', '510051431', 'User', '8432193', '2024-10-28 12:31:45', '10.11.38.105')
ERROR - 2024-10-28 12:33:05 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PROOF ', 'image', '8432199', '510051392', 'User', '8432199', '2024-10-28 12:33:05', '10.11.38.105')
ERROR - 2024-10-28 12:33:48 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'SIGNATURE ', 'image', '8432197', '100004853', 'User', '8432197', '2024-10-28 12:33:48', '10.11.38.105')
ERROR - 2024-10-28 12:34:50 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO ', 'image', '8432194', '100000264', 'User', '8432194', '2024-10-28 12:34:50', '10.11.38.105')
ERROR - 2024-10-28 12:41:55 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 12:49:53 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:49:53 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:49:53 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:22 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:23 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:24 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:58 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:58 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:58 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 12:50:58 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3062
ERROR - 2024-10-28 13:34:14 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:34:14 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:34:19 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:34:19 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:34:54 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:34:54 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:35:00 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3427
ERROR - 2024-10-28 13:38:47 --> 404 Page Not Found: iibfbcbf/agency/Reports/training_details_batch
ERROR - 2024-10-28 13:51:05 --> 404 Page Not Found: iibfbcbf/agency/Reports/get_batch_communication_data_ajax
ERROR - 2024-10-28 13:51:37 --> 404 Page Not Found: iibfbcbf/agency/Reports/get_batch_communication_data_ajax
ERROR - 2024-10-28 14:11:37 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 14:11:55 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 14:29:32 --> Could not find the language line "form_validation_check_captcha_userlogin"
ERROR - 2024-10-28 14:41:56 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 14:41:57 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 15:11:57 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 15:11:59 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 15:18:51 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:09 --> Severity: Warning --> array_walk() expects parameter 2 to be a valid callback, function 'filterData' not found or invalid function name /home/supp0rttest/public_html/staging/application/models/iibfbcbf/Iibf_bcbf_model.php 3790
ERROR - 2024-10-28 15:24:16 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO ', 'image', '8432480', '510620176', 'User', '8432480', '2024-10-28 15:24:16', '10.11.38.105')
ERROR - 2024-10-28 15:41:59 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 15:41:59 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 15:42:01 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 17:02:58 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO || SIGNATURE ', 'image', '8432480', '510620176', 'User', '8432480', '2024-10-28 17:02:58', '10.11.38.105')
ERROR - 2024-10-28 17:12:05 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 17:12:07 --> 404 Page Not Found: Uploads/exam_instruction
ERROR - 2024-10-28 17:54:32 --> Query error: Table 'supp0rttest_iibf_staging.profilelogs' doesn't exist - Invalid query: INSERT INTO `profilelogs` (`title`, `description`, `type`, `regid`, `regnumber`, `editedby`, `editedbyid`, `date`, `ip`) VALUES ('Profile updated successfully', 'PHOTO || SIGNATURE || PROOF || DECLARATION ', 'image', '8432505', '510210923', 'User', '8432505', '2024-10-28 17:54:32', '10.11.38.105')
ERROR - 2024-10-28 18:09:32 --> Severity: Warning --> mcrypt_generic_init(): Key size is 0 /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 83
ERROR - 2024-10-28 18:09:32 --> Severity: Warning --> mcrypt_generic_init(): Key length incorrect /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 83
ERROR - 2024-10-28 18:09:32 --> Severity: Warning --> mcrypt_generic(): 7 is not a valid MCrypt resource /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 84
ERROR - 2024-10-28 18:09:32 --> Severity: Warning --> mcrypt_generic_deinit(): 7 is not a valid MCrypt resource /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 87
ERROR - 2024-10-28 18:09:32 --> Severity: Warning --> mcrypt_module_close(): 7 is not a valid MCrypt resource /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 88
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:40 --> Severity: Warning --> in_array() expects parameter 2 to be array, null given /home/supp0rttest/public_html/staging/application/controllers/CSCVenue.php 367
ERROR - 2024-10-28 18:13:46 --> Severity: Warning --> strtotime() expects parameter 1 to be string, array given /home/supp0rttest/public_html/staging/application/controllers/CSCNonMember.php 1991
ERROR - 2024-10-28 19:10:43 --> 404 Page Not Found: ApplyElearning/favicon.ico
ERROR - 2024-10-28 19:43:58 --> Query error: Column 'total_el_amount' cannot be null - Invalid query: INSERT INTO `exam_invoice` (`pay_txn_id`, `receipt_no`, `exam_code`, `center_code`, `center_name`, `state_of_center`, `member_no`, `app_type`, `exam_period`, `service_code`, `qty`, `state_code`, `state_name`, `tax_type`, `fee_amt`, `total_el_amount`, `total_el_base_amount`, `total_el_gst_amount`, `cgst_rate`, `cgst_amt`, `sgst_rate`, `sgst_amt`, `igst_rate`, `igst_amt`, `cs_total`, `igst_total`, `exempt`, `created_on`) VALUES (6920756, 1638, '1047', '413', 'AJMER', 'RAJ', '801707401', 'O', '3', '999294', '1', '08', 'RAJASTHAN', 'Inter', '300', NULL, 0, 0, '', '', '', '', '18', '54.0', '', '354.0', 'NE', '2024-10-28 19:43:58')
ERROR - 2024-10-28 19:43:58 --> Query error: Column 'total_el_amount' cannot be null - Invalid query: INSERT INTO `exam_invoice` (`pay_txn_id`, `receipt_no`, `exam_code`, `center_code`, `center_name`, `state_of_center`, `member_no`, `app_type`, `exam_period`, `service_code`, `qty`, `state_code`, `state_name`, `tax_type`, `fee_amt`, `total_el_amount`, `total_el_base_amount`, `total_el_gst_amount`, `cgst_rate`, `cgst_amt`, `sgst_rate`, `sgst_amt`, `igst_rate`, `igst_amt`, `cs_total`, `igst_total`, `exempt`, `created_on`) VALUES (6920756, 1638, '1047', '413', 'AJMER', 'RAJ', '801707401', 'O', '3', '999294', '1', '08', 'RAJASTHAN', 'Inter', '300', NULL, 0, 0, '', '', '', '', '18', '54.0', '', '354.0', 'NE', '2024-10-28 19:43:58')
ERROR - 2024-10-28 19:43:58 --> Severity: Warning --> mcrypt_generic_init(): Key size is 0 /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 83
ERROR - 2024-10-28 19:43:58 --> Severity: Warning --> mcrypt_generic_init(): Key length incorrect /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 83
ERROR - 2024-10-28 19:43:58 --> Severity: Warning --> mcrypt_generic(): 9 is not a valid MCrypt resource /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 84
ERROR - 2024-10-28 19:43:58 --> Severity: Warning --> mcrypt_generic_deinit(): 9 is not a valid MCrypt resource /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 87
ERROR - 2024-10-28 19:43:58 --> Severity: Warning --> mcrypt_module_close(): 9 is not a valid MCrypt resource /home/supp0rttest/public_html/staging/application/third_party/SBI_ePay/CryptAES.php 88
ERROR - 2024-10-28 20:07:37 --> 404 Page Not Found: Uploads/exam_instruction
