<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2025-11-17 09:46:37 --> 404 Page Not Found: Careers/sme
ERROR - 2025-11-17 11:42:51 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 11:43:30 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 11:49:29 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 11:51:23 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 11:52:55 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'head_pdc_nz', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 12:06:34 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 12:25:41 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 12:30:00 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 12:30:17 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'Faculty_Member', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 12:38:17 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 16:22:41 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('3', 'Assistant_Director_Academics', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 16:23:14 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('14', 'Faculty_Member_mumbai', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 16:26:21 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'head_pdc_nz', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 16:38:54 --> Query error: Column 'user_agent' cannot be null - Invalid query: INSERT INTO `careers_pages_logs` (`position_id`, `title`, `ip`, `browser`, `user_agent`) VALUES ('7', 'head_pdc_nz', '10.11.38.105', 'UnKnown||UnKnown', NULL)
ERROR - 2025-11-17 17:17:39 --> Severity: Error --> Call to a member function init_payment_request() on null /home/supp0rttest/public_html/staging/application/controllers/ncvet/candidate/Applyexam.php 548
ERROR - 2025-11-17 18:39:16 --> 404 Page Not Found: ApplyElearning/favicon.ico
ERROR - 2025-11-17 18:42:05 --> 404 Page Not Found: ApplyElearning/favicon.ico
